version: '3.9'

services:
  # Banco de dados PostgreSQL para o Zabbix
  postgres-zabbix:
    image: postgres:17
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_DB_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    ports:
      - "5432:5432"
    env_file:
      - .env

  # Servidor Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "10051:10051"
    depends_on:
      - postgres-zabbix
    networks:
      - zabbix-net
    env_file:
      - .env

  # Frontend Zabbix (interface web)
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "80:8080"
    depends_on:
      - postgres-zabbix
      - zabbix-server
    networks:
      - zabbix-net
    env_file:
      - .env

  # Agente Zabbix
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

  # SNMP Traps
  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:latest
    container_name: zabbix-snmptraps
    restart: always
    ports:
      - "162:162/udp"
    environment:
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - zabbix-net

volumes:
  postgres_data:

networks:
  zabbix-net:
